<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\midora-common\Midora.Common\Midora.Common.csproj" />
    <ProjectReference Include="..\..\midora-audio-device\Midora.AudioDevice\Midora.AudioDevice.csproj" />
    <ProjectReference Include="..\..\midora-midi\Midora.Midi\Midora.Midi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Midora.Application.Tests" />
    <InternalsVisibleTo Include="Midora.Audio.Bass" />
  </ItemGroup>

</Project>
