using System.Buffers.Binary;
using System.Text;

namespace Midora.Midi;

public enum StandardMidiFileEventKind : byte
{
    ChannelVoice,
    Meta,
    SystemExclusive
}

public readonly record struct StandardMidiFileEvent
{
    private static readonly UTF8Encoding StrictUtf8 = new(false, true);

    private StandardMidiFileEvent(
        long tick,
        StandardMidiFileEventKind kind,
        MidiMessage message,
        byte type,
        ReadOnlyMemory<byte> data)
    {
        Tick = tick;
        Kind = kind;
        Message = message;
        Type = type;
        Data = data;
    }

    public long Tick { get; }
    public StandardMidiFileEventKind Kind { get; }
    public MidiMessage Message { get; }
    public byte Type { get; }
    public ReadOnlyMemory<byte> Data { get; }

    public static StandardMidiFileEvent ChannelVoice(long tick, MidiMessage message) =>
        new(tick, StandardMidiFileEventKind.ChannelVoice, message, 0, default);

    public static StandardMidiFileEvent Meta(long tick, byte type, ReadOnlySpan<byte> data)
    {
        if (type == StandardMidiFile.EndOfTrackMetaType)
        {
            throw new ArgumentException("End Of Track is generated by the SMF writer.", nameof(type));
        }
        StandardMidiFile.ValidatePayloadLength(data.Length, tick);
        return new(tick, StandardMidiFileEventKind.Meta, default, type, data.ToArray());
    }

    public static StandardMidiFileEvent Text(long tick, byte type, string value)
    {
        ArgumentNullException.ThrowIfNull(value);
        if (type == StandardMidiFile.EndOfTrackMetaType)
            throw new ArgumentException("End Of Track is generated by the SMF writer.", nameof(type));
        StandardMidiFile.ValidatePayloadLength(StrictUtf8.GetByteCount(value), tick);
        return new(tick, StandardMidiFileEventKind.Meta, default, type, StrictUtf8.GetBytes(value));
    }

    public static StandardMidiFileEvent SystemExclusive(
        long tick,
        ReadOnlySpan<byte> data,
        bool continuation = false)
    {
        StandardMidiFile.ValidatePayloadLength(data.Length, tick);
        return new(
            tick,
            StandardMidiFileEventKind.SystemExclusive,
            default,
            continuation ? (byte)0xf7 : (byte)0xf0,
            data.ToArray());
    }
}

public sealed class StandardMidiFileTrack
{
    private readonly StandardMidiFileEvent[] _events;

    public StandardMidiFileTrack(long endTick, IEnumerable<StandardMidiFileEvent> events)
    {
        ArgumentNullException.ThrowIfNull(events);
        EndTick = endTick;
        _events = events.ToArray();
    }

    public long EndTick { get; }
    public IReadOnlyList<StandardMidiFileEvent> Events => _events;
}

public sealed class StandardMidiFileTrackSource
{
    public StandardMidiFileTrackSource(
        long endTick,
        IEnumerable<StandardMidiFileEvent> events,
        string? displayName = null)
    {
        if (endTick < 0) throw new ArgumentOutOfRangeException(nameof(endTick));
        EndTick = endTick;
        Events = events ?? throw new ArgumentNullException(nameof(events));
        DisplayName = displayName;
    }

    public long EndTick { get; }
    public IEnumerable<StandardMidiFileEvent> Events { get; }
    public string? DisplayName { get; }
}

public static partial class StandardMidiFile
{
    public const byte TextMetaType = 0x01;
    public const byte CopyrightMetaType = 0x02;
    public const byte TrackNameMetaType = 0x03;
    public const byte MarkerMetaType = 0x06;
    public const byte MidiPortMetaType = 0x21;
    public const byte EndOfTrackMetaType = 0x2f;
    public const byte SetTempoMetaType = 0x51;
    public const byte TimeSignatureMetaType = 0x58;
    public const byte KeySignatureMetaType = 0x59;
    public const int MaximumVariableLengthValue = 0x0fff_ffff;

    public static byte[] EncodeType1(
        int ticksPerQuarterNote,
        IReadOnlyList<StandardMidiFileTrack> tracks)
    {
        ArgumentNullException.ThrowIfNull(tracks);
        ValidateEncodingHeader(ticksPerQuarterNote, tracks.Count);
        StandardMidiFileTrackSource[] sources = tracks
            .Select(track => track is null
                ? throw new MidoraMidiException("SMF track collection cannot contain null.")
                : new StandardMidiFileTrackSource(track.EndTick, track.Events))
            .ToArray();
        using MemoryStream output = new();
        WriteType1(output, ticksPerQuarterNote, sources);
        byte[] result = output.ToArray();
        ValidateType1(result);
        return result;
    }

    public static StandardMidiFileWriteSummary WriteType1(
        Stream output,
        int ticksPerQuarterNote,
        IReadOnlyList<StandardMidiFileTrackSource> tracks,
        CancellationToken cancellationToken = default,
        IProgress<StandardMidiFileWriteProgress>? progress = null)
    {
        ArgumentNullException.ThrowIfNull(output);
        ArgumentNullException.ThrowIfNull(tracks);
        if (!output.CanWrite || !output.CanSeek)
            throw new ArgumentException("SMF output must be writable and seekable.", nameof(output));
        ValidateEncodingHeader(ticksPerQuarterNote, tracks.Count);
        cancellationToken.ThrowIfCancellationRequested();
        WriteProgress reporter = new(progress, tracks.Count);
        long paddingEvents = 0;
        int paddedTracks = 0;

        WriteAscii(output, "MThd"u8);
        WriteUInt32BigEndian(output, 6);
        WriteUInt16BigEndian(output, 1);
        WriteUInt16BigEndian(output, checked((ushort)tracks.Count));
        WriteUInt16BigEndian(output, checked((ushort)ticksPerQuarterNote));

        for (int trackIndex = 0; trackIndex < tracks.Count; trackIndex++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            StandardMidiFileTrackSource track = tracks[trackIndex];
            if (track is null)
            {
                throw new MidoraMidiException("SMF track collection cannot contain null.");
            }
            if (track.EndTick < 0)
            {
                throw new MidoraMidiException("SMF track End Of Track tick cannot be negative.");
            }

            WriteAscii(output, "MTrk"u8);
            long lengthOffset = output.Position;
            WriteUInt32BigEndian(output, 0);
            long contentOffset = output.Position;
            reporter.TrackIndex = trackIndex;
            reporter.TrackName = track.DisplayName;
            reporter.Events = 0;
            reporter.Report(0, force: trackIndex == 0);
            long trackPadding;
            try
            {
                trackPadding = WriteTrack(output, track.EndTick, track.Events, cancellationToken, reporter);
            }
            catch (StandardMidiFileEncodingException exception)
            {
                exception.TrackIndex = trackIndex;
                exception.TrackName = track.DisplayName;
                throw;
            }
            long endOffset = output.Position;
            long byteCount = checked(endOffset - contentOffset);
            // Every record has already been budgeted before any of its bytes are written.
            output.Position = lengthOffset;
            WriteUInt32BigEndian(output, checked((uint)byteCount));
            output.Position = endOffset;
            paddingEvents = checked(paddingEvents + trackPadding);
            if (trackPadding != 0) paddedTracks++;
            reporter.Report(byteCount, complete: true, force: trackIndex == tracks.Count - 1);
        }
        cancellationToken.ThrowIfCancellationRequested();
        return new(paddingEvents, paddedTracks);
    }

    public static void ValidateType1(ReadOnlySpan<byte> file)
    {
        int position = 0;
        RequireChunkId(file, ref position, "MThd"u8);
        uint headerLength = ReadUInt32BigEndian(file, ref position);
        if (headerLength != 6)
        {
            throw new MidoraMidiException($"SMF header length must be 6, but was {headerLength}.");
        }
        ushort format = ReadUInt16BigEndian(file, ref position);
        ushort trackCount = ReadUInt16BigEndian(file, ref position);
        ushort division = ReadUInt16BigEndian(file, ref position);
        if (format != 1 || trackCount == 0 || division == 0 || (division & 0x8000) != 0)
        {
            throw new MidoraMidiException("The file is not a supported TPQ-based SMF Type 1 file.");
        }

        for (int trackIndex = 0; trackIndex < trackCount; trackIndex++)
        {
            RequireChunkId(file, ref position, "MTrk"u8);
            uint length = ReadUInt32BigEndian(file, ref position);
            if (length > int.MaxValue || position > file.Length - (int)length)
            {
                throw new MidoraMidiException("SMF track chunk length exceeds the remaining file bytes.");
            }
            int trackEnd = position + (int)length;
            long absoluteTick = 0;
            bool foundEndOfTrack = false;

            while (position < trackEnd)
            {
                int delta = ReadVariableLength(file[..trackEnd], ref position);
                absoluteTick = checked(absoluteTick + delta);
                byte status = ReadByte(file[..trackEnd], ref position);
                if (status < 0x80)
                {
                    throw new MidoraMidiException(
                        "Midora SMF compatibility profile requires an explicit status byte for every channel event.");
                }

                if (status == 0xff)
                {
                    byte metaType = ReadByte(file[..trackEnd], ref position);
                    int dataLength = ReadVariableLength(file[..trackEnd], ref position);
                    Skip(file[..trackEnd], ref position, dataLength);
                    if (metaType == EndOfTrackMetaType)
                    {
                        if (dataLength != 0 || foundEndOfTrack || position != trackEnd)
                        {
                            throw new MidoraMidiException("End Of Track must be a single zero-length final event.");
                        }
                        foundEndOfTrack = true;
                    }
                    continue;
                }

                if (status is 0xf0 or 0xf7)
                {
                    int dataLength = ReadVariableLength(file[..trackEnd], ref position);
                    Skip(file[..trackEnd], ref position, dataLength);
                    continue;
                }

                int dataByteCount = (status & 0xf0) switch
                {
                    0x80 or 0x90 or 0xa0 or 0xb0 or 0xe0 => 2,
                    0xc0 or 0xd0 => 1,
                    _ => throw new MidoraMidiException($"Unsupported SMF status byte 0x{status:x2}.")
                };
                for (int dataIndex = 0; dataIndex < dataByteCount; dataIndex++)
                {
                    if (ReadByte(file[..trackEnd], ref position) >= 0x80)
                    {
                        throw new MidoraMidiException("SMF channel data bytes must be 7-bit values.");
                    }
                }
            }

            if (!foundEndOfTrack)
            {
                throw new MidoraMidiException("Every SMF track must contain End Of Track.");
            }
        }

        if (position != file.Length)
        {
            throw new MidoraMidiException("Unexpected bytes follow the declared SMF tracks.");
        }
    }

    private static long WriteTrack(
        Stream output,
        long endTick,
        IEnumerable<StandardMidiFileEvent> events,
        CancellationToken cancellationToken,
        WriteProgress progress)
    {
        long previousTick = 0;
        long writtenBytes = 0;
        long paddingEvents = 0;
        Span<byte> recordBuffer = stackalloc byte[7];
        Span<byte> messageBuffer = recordBuffer[4..];
        foreach (StandardMidiFileEvent value in events)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (value.Tick < previousTick)
            {
                throw new MidoraMidiException("SMF track events must be supplied in nondecreasing tick order.");
            }
            if (value.Tick > endTick)
            {
                throw new MidoraMidiException("SMF event tick cannot be later than End Of Track.");
            }
            // Validate before writing any of this record's potentially extensive padding.
            int messageLength = 0;
            long bodyBytes;
            switch (value.Kind)
            {
                case StandardMidiFileEventKind.ChannelVoice:
                    if (!value.Message.IsChannelVoiceMessage)
                        throw new MidoraMidiException("Only MIDI channel voice messages can be written as channel events.");
                    messageLength = value.Message.WriteTo(messageBuffer);
                    if (messageBuffer[1] >= 0x80 || messageLength == 3 && messageBuffer[2] >= 0x80)
                        throw new MidoraMidiException("SMF channel data bytes must be 7-bit values.");
                    bodyBytes = messageLength;
                    break;
                case StandardMidiFileEventKind.Meta:
                case StandardMidiFileEventKind.SystemExclusive:
                    ValidatePayloadLength(value.Data.Length, value.Tick);
                    if (value.Kind == StandardMidiFileEventKind.SystemExclusive && value.Type is not 0xf0 and not 0xf7)
                        throw new MidoraMidiException("SMF system-exclusive status must be F0 or F7.");
                    bodyBytes = (value.Kind == StandardMidiFileEventKind.Meta ? 2 : 1)
                        + VariableLengthByteCount(value.Data.Length) + (long)value.Data.Length;
                    break;
                default:
                    throw new MidoraMidiException($"Unknown SMF event kind {value.Kind}.");
            }
            long deltaTick = value.Tick - previousTick;
            previousTick = value.Tick;
            if (value.Kind == StandardMidiFileEventKind.ChannelVoice && deltaTick <= MaximumVariableLengthValue)
            {
                // Proven bounds: writtenBytes <= uint.MaxValue, and this record has at most 7 bytes.
                // Same budget/EOT rule as ReserveTrackRecord, without a padding plan on the hot path.
                long next = writtenBytes + VariableLengthByteCount((int)deltaTick) + messageLength;
                if (next > MaximumTrackDataLength - 4) ThrowTrackSizeLimit(next + 4, value.Tick);
                writtenBytes = next;
                int first = EncodeVariableLength(recordBuffer[..4], (int)deltaTick);
                output.Write(recordBuffer[first..(4 + messageLength)]);
            }
            else
            {
                long precedingBytes = writtenBytes;
                DeltaEncoding delta = ReserveTrackRecord(ref writtenBytes, deltaTick,
                    bodyBytes, isEndOfTrack: false, value.Tick);
                paddingEvents += delta.PaddingEvents;
                WriteDelta(output, delta, cancellationToken, progress, precedingBytes);
                switch (value.Kind)
                {
                    case StandardMidiFileEventKind.ChannelVoice:
                        output.Write(messageBuffer[..messageLength]);
                        break;
                    case StandardMidiFileEventKind.Meta:
                        output.WriteByte(0xff);
                        output.WriteByte(value.Type);
                        WriteVariableLength(output, value.Data.Length);
                        WritePayload(output, value.Data.Span, cancellationToken, progress, writtenBytes - value.Data.Length);
                        break;
                    case StandardMidiFileEventKind.SystemExclusive:
                        output.WriteByte(value.Type);
                        WriteVariableLength(output, value.Data.Length);
                        WritePayload(output, value.Data.Span, cancellationToken, progress, writtenBytes - value.Data.Length);
                        break;
                    default:
                        throw new MidoraMidiException($"Unknown SMF event kind {value.Kind}.");
                }
            }
            progress.Events++;
            if ((progress.Events & 4095) == 0) progress.Report(writtenBytes);
        }

        cancellationToken.ThrowIfCancellationRequested();
        long beforeEnd = writtenBytes;
        DeltaEncoding endDelta = ReserveTrackRecord(ref writtenBytes, endTick - previousTick,
            3, isEndOfTrack: true, endTick);
        WriteDelta(output, endDelta, cancellationToken, progress, beforeEnd);
        output.Write([0xff, EndOfTrackMetaType, 0x00]);
        return checked(paddingEvents + endDelta.PaddingEvents);
    }

    private static void WriteVariableLength(Stream output, long value)
    {
        if (value is < 0 or > MaximumVariableLengthValue)
        {
            throw new MidoraMidiException(
                $"SMF variable-length quantity must be in the range 0..{MaximumVariableLengthValue}, but was {value}.");
        }
        Span<byte> buffer = stackalloc byte[4];
        int first = EncodeVariableLength(buffer, (int)value);
        output.Write(buffer[first..]);
    }

    private static int EncodeVariableLength(Span<byte> buffer, int value)
    {
        int index = 3;
        buffer[index] = (byte)(value & 0x7f);
        while ((value >>= 7) != 0) buffer[--index] = (byte)((value & 0x7f) | 0x80);
        return index;
    }

    private static int ReadVariableLength(ReadOnlySpan<byte> source, ref int position)
    {
        int value = 0;
        for (int index = 0; index < 4; index++)
        {
            byte current = ReadByte(source, ref position);
            value = (value << 7) | (current & 0x7f);
            if ((current & 0x80) == 0)
            {
                return value;
            }
        }
        throw new MidoraMidiException("SMF variable-length quantity exceeds four bytes.");
    }

    private static void WriteAscii(Stream output, ReadOnlySpan<byte> value) => output.Write(value);

    private static void WriteUInt16BigEndian(Stream output, ushort value)
    {
        Span<byte> bytes = stackalloc byte[2];
        BinaryPrimitives.WriteUInt16BigEndian(bytes, value);
        output.Write(bytes);
    }

    private static void WriteUInt32BigEndian(Stream output, uint value)
    {
        Span<byte> bytes = stackalloc byte[4];
        BinaryPrimitives.WriteUInt32BigEndian(bytes, value);
        output.Write(bytes);
    }

    private static ushort ReadUInt16BigEndian(ReadOnlySpan<byte> source, ref int position)
    {
        if (position > source.Length - 2)
        {
            throw new MidoraMidiException("Unexpected end of SMF data.");
        }
        ushort result = BinaryPrimitives.ReadUInt16BigEndian(source[position..]);
        position += 2;
        return result;
    }

    private static uint ReadUInt32BigEndian(ReadOnlySpan<byte> source, ref int position)
    {
        if (position > source.Length - 4)
        {
            throw new MidoraMidiException("Unexpected end of SMF data.");
        }
        uint result = BinaryPrimitives.ReadUInt32BigEndian(source[position..]);
        position += 4;
        return result;
    }

    private static byte ReadByte(ReadOnlySpan<byte> source, ref int position)
    {
        if ((uint)position >= (uint)source.Length)
        {
            throw new MidoraMidiException("Unexpected end of SMF data.");
        }
        return source[position++];
    }

    private static void Skip(ReadOnlySpan<byte> source, ref int position, int count)
    {
        if (count < 0 || position > source.Length - count)
        {
            throw new MidoraMidiException("SMF event data length exceeds the track chunk.");
        }
        position += count;
    }

    private static void RequireChunkId(ReadOnlySpan<byte> source, ref int position, ReadOnlySpan<byte> expected)
    {
        if (position > source.Length - expected.Length
            || !source.Slice(position, expected.Length).SequenceEqual(expected))
        {
            throw new MidoraMidiException($"Expected SMF chunk '{Encoding.ASCII.GetString(expected)}'.");
        }
        position += expected.Length;
    }
}
